
general =
{
	name = "roon airplay";
	output_backend = "pipe";
  port = 7000;
	ignore_volume_control = "yes";
};

sessioncontrol =
{
	run_this_before_entering_active_state = "/opt/scripts/notify.sh POST";
	run_this_after_exiting_active_state = "/opt/scripts/notify.sh DELETE";
	active_state_timeout = 2.0;
};

pipe =
{
	name = "/tmp/shairport-sync-audio";
	output_rate = 44100;
	output_format = "S16_LE";
	output_channels = 2;
};

metadata =
{
	enabled = "yes";
	include_cover_art = "yes";
	cover_art_cache_directory = "/tmp/shairport-sync/.cache/coverart";
	pipe_name = "/tmp/shairport-sync-metadata";
	pipe_timeout = 5000;
};
