name: CD

on:
  release:
    types: [published]
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    uses: docker/github-builder/.github/workflows/build.yml@v1
    permissions:
      contents: read
      id-token: write
    with:
      output: image
      push: true
      context: .
      file: app/roon-web-api/Dockerfile
      platforms: linux/amd64,linux/arm64
      target: runtime
      cache: true
      cache-scope: roon-web-stack
      meta-images: nihiluxorg/roon-web-stack
      meta-tags: |
        type=semver,pattern=v{{version}}
      set-meta-labels: true
    secrets:
      registry-auths: |
        - registry: docker.io
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PAT }}
